const TOKEN_KEY='epmToken',USER_KEY='epmUser';
function installMobileStyles(){if(document.getElementById('epm-mobile-css'))return;const l=document.createElement('link');l.id='epm-mobile-css';l.rel='stylesheet';l.href='mobile.css';document.head.appendChild(l)}
function getToken(){return localStorage.getItem(TOKEN_KEY)||''}
function getUser(){try{return JSON.parse(localStorage.getItem(USER_KEY)||'null')}catch{return null}}
function saveSession(data){if(!data?.token||!data?.user)return;localStorage.setItem(TOKEN_KEY,data.token);localStorage.setItem(USER_KEY,JSON.stringify(data.user));localStorage.setItem('user',JSON.stringify(data.user));syncBattlePassUI()}
function resetNewUserAvatar(user){if(!user?.id)return;localStorage.removeItem(`epmAvatar:${user.id}`)}
function escapeHtml(s=''){return String(s).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]))}
function logout(){const token=getToken();fetch('/api/auth/logout',{method:'POST',headers:{Authorization:'Bearer '+token}}).catch(()=>{});localStorage.removeItem(TOKEN_KEY);localStorage.removeItem(USER_KEY);localStorage.removeItem('user');location.href='index.html'}
function syncHeader(user){const box=document.querySelector('.account-links');if(!box)return;if(!user){box.innerHTML='<a href="login.html">Войти</a><a class="account-register" href="register.html">Регистрация</a>';return}box.innerHTML=`<a href="profile.html" class="profile-header-link">${escapeHtml(user.nickname||'Профиль')}</a><a class="account-register logout-header-link" href="#">Выйти</a>`;const link=box.querySelector('.logout-header-link');if(link)link.onclick=e=>{e.preventDefault();logout()}}
function syncBattlePassUI(){try{const u=getUser();if(!u?.id)return;const s=JSON.parse(localStorage.getItem(`epmBattlePass:${u.id}`)||'{"xp":0}');const xp=Math.max(0,Number(s.xp)||0);const level=xp>=2000?20:Math.min(20,Math.floor(xp/100)+1);const el=document.getElementById('level');if(el)el.textContent=level;const bp=document.getElementById('profileBattlePassLevel');if(bp)bp.textContent=level;const xpEl=document.getElementById('profileBattlePassXP');if(xpEl)xpEl.textContent=xp+' XP'}catch{}}
async function restoreSession(){const token=getToken(),cachedUser=getUser();if(!token){syncHeader(null);window.epmUser=null;return null}try{const r=await fetch('/api/auth/me',{headers:{Authorization:'Bearer '+token},cache:'no-store'});if(r.ok){const d=await r.json();saveSession({token,user:d.user});syncHeader(d.user);window.epmUser=d.user;syncBattlePassUI();return d.user}if(r.status===401||r.status===403){localStorage.removeItem(TOKEN_KEY);localStorage.removeItem(USER_KEY);localStorage.removeItem('user');syncHeader(null);window.epmUser=null;return null}if(cachedUser){syncHeader(cachedUser);window.epmUser=cachedUser;syncBattlePassUI();return cachedUser}syncHeader(null);window.epmUser=null;return null}catch{if(cachedUser){syncHeader(cachedUser);window.epmUser=cachedUser;syncBattlePassUI();return cachedUser}syncHeader(null);window.epmUser=null;return null}}
async function setupAuth(mode){const form=document.getElementById('form'),error=document.getElementById('error');if(!form)return;const existing=await restoreSession();if(existing){location.href='profile.html';return}form.onsubmit=async e=>{e.preventDefault();error.textContent='';const nickname=document.getElementById('nickname').value.trim(),password=document.getElementById('password').value;if(mode==='register'&&password!==document.getElementById('confirm').value){error.textContent='Пароли не совпадают';return}try{const r=await fetch('/api/auth/'+mode,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({nickname,password})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Произошла ошибка');if(mode==='register')resetNewUserAvatar(d.user);saveSession(d);syncHeader(d.user);location.href='profile.html'}catch(err){error.textContent=err.message||'Сервер недоступен'}}}
document.addEventListener('DOMContentLoaded',()=>{installMobileStyles();restoreSession()});window.addEventListener('epm:battlepass',syncBattlePassUI);window.EPMAuth={getToken,getUser,saveSession,restoreSession,logout,syncHeader,syncBattlePassUI};