const BASE_KEY='epmBattlePass';
const PREMIUM_KEY='epmPremiumBattlePass';
const MAX_LEVEL=20;
const XP_PER_LEVEL=100;
const rewards=[['1','🪙','Старт','10 монет'],['2','⛏️','Ресурсы','Набор ресурсов'],['3','🛡️','Защита','Защитный набор'],['4','💎','Кристалл','15 монет'],['5','🎁','Ящик','Обычный ящик'],['6','⚔️','Оружие','Боевой набор'],['7','🪙','Монеты','25 монет'],['8','🧱','Строитель','Набор строителя'],['9','💎','Кристалл','30 монет'],['10','👑','Elite','Особая награда'],['11','🔥','Огонь','Огненный набор'],['12','🎁','Ящик','Редкий ящик'],['13','🪙','Монеты','40 монет'],['14','⚡','Энергия','Энергия EPM'],['15','🏆','Champion','Особая награда'],['16','💎','Алмаз','Алмазный набор'],['17','🛡️','Страж','Награда стража'],['18','🪙','Монеты','60 монет'],['19','🎁','Ящик','Эпический ящик'],['20','👑','EPM Master','Финальная награда']];
const premiumRewards=[['1','💎','Premium Start','20 монет'],['5','👑','Royal Kit','Королевский набор'],['10','🔥','Fire Title','Огненный титул'],['15','⚡','EPM Energy','Энергия EPM'],['20','🏆','EPM Legend','Легендарная награда']];
function currentUser(){try{return JSON.parse(localStorage.getItem('epmUser')||localStorage.getItem('user')||'null')}catch{return null}}
function storageKey(base){const u=currentUser();return u?.id?`${base}:${u.id}`:base+':guest'}
function getState(){try{const s=JSON.parse(localStorage.getItem(storageKey(BASE_KEY)));return s&&typeof s==='object'?{xp:Math.max(0,Number(s.xp)||0),level:Math.min(MAX_LEVEL,Math.max(1,Number(s.level)||1)),claimed:Array.isArray(s.claimed)?s.claimed:[],premiumClaimed:Array.isArray(s.premiumClaimed)?s.premiumClaimed:[]}:{xp:0,level:1,claimed:[],premiumClaimed:[]}}catch{return {xp:0,level:1,claimed:[],premiumClaimed:[]}}}
function saveState(s){s.level=s.xp>=MAX_LEVEL*XP_PER_LEVEL?MAX_LEVEL:Math.min(MAX_LEVEL,Math.floor(s.xp/XP_PER_LEVEL)+1);localStorage.setItem(storageKey(BASE_KEY),JSON.stringify(s));return s}
function levelFromXP(xp){return xp>=MAX_LEVEL*XP_PER_LEVEL?MAX_LEVEL:Math.min(MAX_LEVEL,Math.floor(xp/XP_PER_LEVEL)+1)}
function render(){const s=getState(),level=levelFromXP(s.xp),inside=level>=MAX_LEVEL?100:s.xp%XP_PER_LEVEL;const a=document.getElementById('levelText'),b=document.getElementById('xpText'),fill=document.getElementById('fill'),list=document.getElementById('rewards');if(a)a.textContent='Уровень '+level;if(b)b.textContent=(level>=MAX_LEVEL?100:inside)+' / 100 XP';if(fill)fill.style.width=(level>=MAX_LEVEL?100:inside)+'%';if(list)list.innerHTML=rewards.map(r=>{const n=+r[0],open=n<=level,claimed=s.claimed.includes(n);return `<article class="reward ${[10,15,20].includes(n)?'premium ':''}${open?'':'locked'} ${claimed?'claimed':''}"><span class="reward-num">УРОВЕНЬ ${n}</span><div class="reward-icon">${r[1]}</div><b>${r[2]}</b><small>${claimed?'✓ Получено':open?'Доступно':'🔒 Заблокировано'}</small>${open&&!claimed?`<button class="reward-claim" data-level="${n}">Забрать</button>`:''}</article>`}).join('');document.querySelectorAll('.reward-claim').forEach(btn=>btn.onclick=()=>claimReward(+btn.dataset.level,false));renderPremium(s,level);syncPremium()}
function renderPremium(s,level){const box=document.getElementById('premiumRewards');if(!box)return;const active=localStorage.getItem(storageKey(PREMIUM_KEY))==='true';if(!active){box.style.display='none';return}box.style.display='grid';box.innerHTML=premiumRewards.map(r=>{const n=r[0],open=n<=level,claimed=s.premiumClaimed.includes(n);return `<article class="reward premium ${open?'':'locked'} ${claimed?'claimed':''}"><span class="reward-num">PREMIUM · LVL ${n}</span><div class="reward-icon">${r[1]}</div><b>${r[2]}</b><small>${claimed?'✓ Получено':open?'Доступно':'🔒 Заблокировано'}</small>${open&&!claimed?`<button class="reward-claim" data-level="${n}" data-premium="1">Забрать</button>`:''}</article>`}).join('');box.querySelectorAll('.reward-claim').forEach(btn=>btn.onclick=()=>claimReward(+btn.dataset.level,true))}
function claimReward(level,premium){const s=getState(),current=levelFromXP(s.xp);if(level>current)return;if(premium&&localStorage.getItem(storageKey(PREMIUM_KEY))!=='true')return;if(premium){if(s.premiumClaimed.includes(level))return;s.premiumClaimed.push(level)}else{if(s.claimed.includes(level))return;s.claimed.push(level)}saveState(s);render()}
function addXP(amount){const n=Number(amount);if(!Number.isFinite(n)||n<=0)return getState();const s=getState();s.xp=Math.min(MAX_LEVEL*XP_PER_LEVEL,s.xp+n);saveState(s);render();return s}
function getBattlePass(){const s=getState();return {...s,level:levelFromXP(s.xp),premium:localStorage.getItem(storageKey(PREMIUM_KEY))==='true'}}
function syncPremium(){const btn=document.getElementById('premiumBuy'),status=document.getElementById('premiumStatus');const active=localStorage.getItem(storageKey(PREMIUM_KEY))==='true';if(btn){btn.textContent=active?'Премиум активен':'Купить за 170 ₽';btn.disabled=active}if(status)status.style.display=active?'block':'none'}
function activatePremium(){if(!currentUser()){location.href='login.html';return false}if(localStorage.getItem(storageKey(PREMIUM_KEY))==='true')return true;localStorage.setItem(storageKey(PREMIUM_KEY),'true');syncPremium();render();return true}
document.addEventListener('DOMContentLoaded',()=>{render();const btn=document.getElementById('premiumBuy');if(btn)btn.onclick=activatePremium});window.addEventListener('storage',()=>{render()});window.EPMBattlePass={getState:getBattlePass,addXP,claimReward,activatePremium,render};